### ISSUE TITLE
How to set custom size

### ISSUE THREAD

**Issue by muxinxy** [zhbhun/idify#8]
How to set custom size, like 130x160.

**Comment by zhbhun** [comment]
Customizable size can be set in the size of the crop.

![image](https://github.com/zhbhun/idify/assets/1996891/17839082-9b91-46c3-a4b0-1286a7aa4c38)

**Comment by muxinxy** [comment]
> Customizable size can be set in the size of the crop.
> 
> ![image](https://private-user-images.githubusercontent.com/1996891/296962698-17839082-9b91-46c3-a4b0-1286a7aa4c38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDEyNDEsIm5iZiI6MTcwNTUwMDk0MSwicGF0aCI6Ii8xOTk2ODkxLzI5Njk2MjY5OC0xNzgzOTA4Mi05YjkxLTQ2YzMtYTRiMC0xMjg2YTdhYTRjMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMTQxNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNmZjJmNjdiMGI3NTA3OTQ0NWYzYTVlYzFiZjI1ZDAxYzAyYjVkMDIwMDM4MDNmZjFjNjNkODQ2NGE5NzBlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8n_JIIJXmu3nbRQjmKp8Kzj8RyYB8l1jwzkOCZtO-eg)

I found the cause of the problem. I couldn't find the custom option with the mouse. The custom option was hidden. I found it with the arrow keys on the keyboard.

![image](https://github.com/zhbhun/idify/assets/32673109/4fe367f7-5ce4-4d27-96fe-add3b54e67ca)

**Comment by zhbhun** [comment]
It should be a caching problem, refresh the page and try again!
