### ISSUE TITLE
When starting the project, it prompts that the script 'dev' is missing.

### ISSUE THREAD

**Issue by alones58** [zhbhun/idify#9]
Hello, I'm very grateful for your project. I followed your instructions to execute "pnpm install" and "npm run dev" during deployment, but I received the following error message: missing script: "dev". Could you please tell me what went wrong? Also, the project was deployed using pnpm, so why has the start command changed to "npm run dev"?

**Comment by zhbhun** [comment]
monorepo was used here, with multiple packages.

```
cd packages/web
npm run dev
```
